version: '3.8'

services:
  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge
